# Generated by Django 4.2.4 on 2023-11-07 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_foodcriticrestaurantreview_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='foodcriticrestaurantreview',
            unique_together={('reviewer_name', 'restaurant')},
        ),
        migrations.AlterUniqueTogether(
            name='regularrestaurantreview',
            unique_together={('reviewer_name', 'restaurant')},
        ),
    ]
