# Generated by Django 4.2.4 on 2023-11-23 14:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='last_update',
            new_name='last_updated',
        ),
        migrations.AlterField(
            model_name='director',
            name='years_of_experience',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('Comedy', 'Comedy'), ('Action', 'Action'), ('Other', 'Other'), ('Drama', 'Drama')], default='Other', max_length=6),
        ),
    ]
