# Generated by Django 4.2.4 on 2023-11-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_last_update_movie_last_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('Drama', 'Drama'), ('Action', 'Action'), ('Comedy', 'Comedy'), ('Other', 'Other')], default='Other', max_length=6),
        ),
    ]
