# Generated by Django 4.2.4 on 2023-11-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=3),
            preserve_default=False,
        ),
    ]
