# Generated by Django 4.2.4 on 2023-11-20 16:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_order_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='orders', to='main_app.product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='main_app.profile'),
        ),
        migrations.AlterField(
            model_name='product',
            name='in_stock',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
