# Generated by Django 4.2.4 on 2023-11-07 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeldbladeDemonHunter',
            new_name='FelbladeDemonHunter',
        ),
    ]
