# Generated by Django 4.2.4 on 2023-10-17 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_text',
            field=models.TextField(null=True),
        ),
    ]
