# Generated by Django 4.2.4 on 2023-11-23 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_brand_carmodel_remove_city_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='origin_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='main_app.country'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='main_app.brand'),
        ),
        migrations.AlterField(
            model_name='country',
            name='continent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country', to='main_app.continent'),
        ),
    ]
