# Generated by Django 4.2.4 on 2023-10-23 17:54

from django.db import migrations

def set_price(apps, schema_editor):

    MULTIPLE = 120
    smartphone_model = apps.get_model('main_app', 'Smartphone')

    for smartphone in smartphone_model.objects.all():
        smartphone.price = len(smartphone.brand) * MULTIPLE
        smartphone.save()

def set_category(apps, schema_editor):
    smartphone_model = apps.get_model('main_app', 'Smartphone')

    for smartphone in smartphone_model.objects.all():
        if smartphone.price >= 750:
            smartphone.category = 'Expensive'
        else:
            smartphone.category = 'Cheap'

        smartphone.save()

def set_category_price(apps, schema_editor):
    set_price(apps, schema_editor)
    set_category(apps, schema_editor)

def reverse_func(apps, schema_editor):
    smartphone_model = apps.get_model('main_app', 'Smartphone')

    category_default = smartphone_model._meta.get_field('category').default
    for smartphone in smartphone_model.objects.all():
        smartphone.price = 0
        smartphone.category = category_default #
        smartphone.save() # todo bulk update
class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_smartphone'),
    ]

    operations = [
        migrations.RunPython(set_category_price,reverse_code=reverse_func),
    ]
