# Generated by Django 4.2.4 on 2023-10-23 18:50


from django.db import migrations
from django.utils import timezone


def set_delivery_date(apps, schema_editor):
    order_model = apps.get_model('main_app', 'Order')


    for order in order_model.objects.all():
        if order.status == 'Pending':
            order.delivery += timezone.timedelta(days=3)
            order.save()
        elif order.status == 'Completed':
            order.warranty = '24 months'
            order.save()
        elif order.status == 'Cancelled':
            order.delete(order)
def reverse_func(apps, schema_editor):
    order_model = apps.get_model('main_app', 'Order')
    for order in order_model.objects.all():
        if order.status == 'Pending':
            order.delivery = None
            order.save()
        elif order.status == 'Completed':
            order.warranty = 'No warranty'
            order.save()




class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_order'),
    ]

    operations = [
        migrations.RunPython(code=set_delivery_date, reverse_code=reverse_func),
    ]
