# Generated by Django 4.2.4 on 2023-10-23 20:37

from django.db import migrations

def change_rarity(apps, schema_editor):
    item_model = apps.get_model('main_app', 'Item')
    items_to_update = item_model.objects.all()

    for item in items_to_update:
        if item.price <= 10:
            item.rarity = 'Rare'
        elif item.price <= 20:
            item.rarity = 'Very rare'
        elif item.price <= 30:
            item.rarity = 'Extremely rare'
        else:
            item.rarity = 'Mega rare'

    item_model.objects.bulk_update(items_to_update, ['rarity'])
def reverse_func(apps, schema_editor):
    item_model = apps.get_model('main_app', 'Item')
    rarity_default = item_model._meta.get_field('rarity').default

    for item in item_model.objects.all():
        item.rarity = rarity_default # no rarity
    item_model.objects.bulk_update(item_model, ['rarity'])

class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_item'),
    ]

    operations = [
        migrations.RunPython(change_rarity, reverse_func),
    ]
